### ISSUE TITLE
exeファイルの詳細タブのバージョンが1.0.0.0のままになっている

### ISSUE THREAD

**Issue by arigayas** [kawaba-takusu/TextManualSorter#4]
### スクリーンショット
![image](https://user-images.githubusercontent.com/11251874/42318537-4c9c5770-808a-11e8-8676-c12fca72ae31.png)
比較としてGitHubDesktopSetup.exeを配置しました。

**Comment by kawaba-takusu** [comment]
ファイルバージョンの修正をしました。

VB ってバージョンを指定するところがなぜか二ケ所あって、その両方に同じバージョンを指定しました。

AssemblyInfo.vb 内の設定です。

**Comment by arigayas** [comment]
![image](https://user-images.githubusercontent.com/11251874/42381845-54e11f72-816d-11e8-9441-b3a59cf4797c.png)
修正を確認しました！
